name: Cypress tests

on: [pull_request]

jobs:
  test:
    if: ${{ github.event.pull_request.head.repo.full_name == 'Sage/carbon' }} 
    name: Cypress regression
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 20 copies of the current job in parallel
        containers: [
            1, 2, 3, 4, 5, 
            6, 7, 8, 9, 10, 
            11, 12, 13, 14, 15, 
            16, 17, 18, 19, 20
            ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v1.24.3
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:9001'
          wait-on-timeout: 250
          record: true
          parallel: true
          group: ubuntu-regression
          spec: './cypress/features/regression/**/*.feature'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: 'true'
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fork-test:
    if: ${{ github.event.pull_request.head.repo.full_name != 'Sage/carbon' }}  
    name: Cypress regression on forked PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Cypress run
        uses: cypress-io/github-action@v1.24.3
        with:
          start: npm start
          wait-on: "http://localhost:9001"
          wait-on-timeout: 250
          record: true
          parallel: true
          group: ubuntu-regression-fork
          spec: './cypress/features/regression/**/*.feature'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: 'true'
